from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AgentRequest(BaseModel):
    user_id: str = Field(
        ...,
        description="Unique user identifier for the request.",
        examples=["user_001"],
    )
    session_id: str = Field(
        ...,
        description="Conversation session identifier used for short-term memory tracking.",
        examples=["session_001"],
    )
    message: str = Field(
        ...,
        min_length=2,
        max_length=4000,
        description="The user query or task request to be processed by the agent runtime.",
        examples=["I need help with a billing issue and this is urgent."],
    )
    use_case: str = Field(
        default="customer_support",
        description=(
            "Domain template used to route the workflow. "
            "Supported values: customer_support, healthcare_copilot, knowledge_assistant, "
            "research_assistant, sales_assistant, hr_assistant, it_helpdesk, operations_assistant"
        ),
        examples=["customer_support"],
    )
    use_retrieval: bool = Field(
        default=True,
        description="Whether retrieval-augmented context lookup should be enabled.",
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Optional metadata such as channel, source system, or tenant information.",
        examples=[{"channel": "web"}],
    )


class AgentResponse(BaseModel):
    use_case: str = Field(description="Selected domain template.")
    use_case_category: str = Field(description="High-level category for the selected use case.")
    intent: str = Field(description="Detected workflow intent.")
    conversation_signal: str = Field(
        description="Detected interaction signal such as urgent, high_friction, needs_guidance, or normal."
    )
    recommended_action: str = Field(description="Suggested next-best action generated by the runtime.")
    retrieved_context: List[str] = Field(description="Retrieved context snippets used to support the response.")
    answer: str = Field(description="Generated domain-aware response.")
    memory: List[str] = Field(description="Recent session memory messages.")
    tool_candidates: List[str] = Field(description="Suggested tool or system integrations relevant to the use case.")
    trace: Dict[str, Any] = Field(description="Execution trace and runtime metadata.")

